### ISSUE TITLE
[Feature Request] Flatpak/snap/Appimage support

### ISSUE THREAD

**Issue by dtantono** [Suwayomi/Tachidesk-Sorayomi#113]
**Is your feature request related to a problem? Please describe.**
deb support is fine. But, it will be wonderful to cover multiple distributions.

**Describe the solution you'd like**
 So, Flatpak/snap/appimage will be great

**Describe alternatives you've considered**
aur package is okay. But, not everybody likes that

**Additional context**

**Comment by DattatreyaReddy** [comment]
We use Github actions to build & deploy apps (Though AUR is updated manually, one of the reasons why it gets updated slowly), but manually deploying apps to other Package distributions is something we would like to avoid.

I've gone through GitHub actions to check if there is an automated way to publish apps but I can't find any. So we need to wait until there is any action to automate this process.

**Comment by dtantono** [comment]
@DattatreyaReddy I cannot see this app on Flathub/snap. why this issue closed?

**Comment by DattatreyaReddy** [comment]
Well we don't have any plans on releasing it in FlatHub or snap for now

**Comment by dtantono** [comment]
@DattatreyaReddy  That is regrettable. It will be nice to use this app to read manga directly on Flatpak with Steam deck rather than long way with virtualization

**Comment by DattatreyaReddy** [comment]
You could help us with this

**Comment by DattatreyaReddy** [comment]
If you could find any automation tool or any other way to deploy it automatically do reach out to us in discord
