### ISSUE TITLE
Downloads tab showing "Something went wrong!"

### ISSUE THREAD

**Issue by codevski** [Suwayomi/Tachidesk-Sorayomi#120]
**Describe the bug**
When downloading, the downloads tab isn't showing anything. Just a something went wrong.

**To Reproduce**
1. Find a manga
2. Download a chapter
3. Nothing in Downloads during queue but you can see it on tachidesk server.

**Expected behavior**
See the download queue

**Screenshots**
Background is the tachidesk server webUI, middle is sorayomi and on the right is another app that uses tachidesk server
![image](https://user-images.githubusercontent.com/1435321/218900061-70c76c58-a805-4acb-96d9-ad1786a2219b.png)

## Device information (Server)
- Tachidesk version: (v0.7.0)
- Server Operating System: (Docker)
## Device information (Client)
- Client version: (0.4.1
- Client Type: (Linux)
- Client Operating System: (Archlinux)
- Client Specifications: (Desktop)

**Comment by vouvoltar** [comment]
Websockets are used for the download. If you're using a reverse proxy, make sure that WebSockets are enabled.

**Comment by DattatreyaReddy** [comment]
This is a known bug where if you enable basic auth, you won't be able to access the Download screen web socket.

Need a fix from server side

**Comment by qu1ck** [comment]
And yet Tachidesk-JUI manages to show downloads with basic auth enabled just fine.
Is it limitation of flutter apis?

**Comment by DattatreyaReddy** [comment]
Its a limitation of Flutter Web.
we can make it work on other platforms (I'll try to fix that in the next update)

**Comment by DattatreyaReddy** [comment]
#245 will fix this issue on All platforms except the Web.
I'm closing this issue along with the PR. if you require WebSockets in Sorayomi web you can rise this Issue again.
