### ISSUE TITLE
scrolling speed too high in macos

### ISSUE THREAD

**Issue by imeed166** [Suwayomi/Tachidesk-Sorayomi#137]
**Describe the bug**
When scrolling in mac os 12.3.1, the scrolling speed is too sensitive and scrolls too fast compared to scrolling page in chrome.

**To Reproduce**
1. try scrolling a manga page in sorayomi
2. try scrolling the same manga page in chrome 

**Expected behavior**
The scrolling behaviour is the same as the scrolling behaviour in macos.

## Device information (Server)
- Tachidesk version: Server: v0.7.0 + WebUI: r983
- Server Operating System: mac os 12.3.1
- Server Desktop Environment: N/A or (Example: Gnome 40)
- Server JVM version: bundled with win32 or (Example: Java 8 Update 281 or OpenJDK 8u281)
## Device information (Client)
- Client version: 0.4.3
- Client Type: Mac app/dmg
- Client Operating System: mac os 12.3.1
- Client Specifications: macbook pro retina 13-inch, early 2015

**Comment by DattatreyaReddy** [comment]
Are you talking about the Trackpad scroll speed?

**Comment by DattatreyaReddy** [comment]
If it is tap to scroll or click to scroll they will follow a An algorithm called Magic Scroll where in the image will scroll to 80% of screen or the end of page.

If it is about Trackpad that's the default speed from flutter itself

**Comment by imeed166** [comment]
It's the trackpad speed

**Comment by DattatreyaReddy** [comment]
Actually, On my mac, I found chrome to be more sensitive in comparison with App

**Comment by imeed166** [comment]
What I noticed, is that sometimes, when my finger leaves the trackpad, there is an unintended scroll that doesn't happen in chrome. In terms of speed, it's practically the same.

**Comment by DattatreyaReddy** [comment]
Seems like the scroll distance covered by the chrome & App seems to be different

**Comment by DattatreyaReddy** [comment]
But is this really a problem?

**Comment by imeed166** [comment]
In my opinion, yes, because I only use the "continuous vertical" mode when reading, and I scroll all the time, making unintentional scrolling a common enough occurrence for me to create this issue.

**Comment by DattatreyaReddy** [comment]
https://user-images.githubusercontent.com/58727124/220433204-5a6c0ceb-8e3a-4bac-b9ad-c0f4194a54d0.mov

**Comment by DattatreyaReddy** [comment]
https://user-images.githubusercontent.com/58727124/220433508-8950e44b-28b4-4d05-a0b3-962374986b19.mov

Idk why this is happening but the scroll speed seems to be working differently for everyone

**Comment by DattatreyaReddy** [comment]
BTW one doubt.

> try scrolling the same manga page in chrome
by this statement do you mean WebUI or Sorayomi Web?

**Comment by DattatreyaReddy** [comment]
I don't think I could fix it as I could not reproduce your issue as shown in the above videos

**Comment by imeed166** [comment]
I was comparing to the scrolling in the website source.

**Comment by imeed166** [comment]
> Also, I don't think we need to fix a platform-specific problem if it is not a major one as we have almost 6 platforms

I understand, thank you for your replies.

**Comment by DattatreyaReddy** [comment]
source website as in asurascans?

**Comment by imeed166** [comment]
I was using mangasee123.com

**Comment by imeed166** [comment]
I wasn't using tachidesk or sorayomi in chrome, just the normal website.

**Comment by DattatreyaReddy** [comment]
I'm sorry, but we can't do what you've asked for since it is not an issue in the App.

you could adjust your trackpad speed from settings to get your required speed

**Comment by imeed166** [comment]
I understand, It's alright, thank you for giving alternative solutions.

**Comment by DattatreyaReddy** [comment]
- you could use arrow keys or WASD (game keys) to scroll
- you could also click on the reader to scroll (check navigation layout option)

**Comment by DattatreyaReddy** [comment]
Thank you for using the App and also providing the Feedback

**Comment by imeed166** [comment]
I'm not commenting to open the issue again, this is just for your information, maybe It'll be useful in the future. 

I've actually determined where the problem was, I was using an external display when using tachidesk sorayomi macos desktop app, when I moved the window to my mac screen, it reverted to normal scrolling speed. So I guess the display was the cause of the increase in the scroll speed.

**Comment by imeed166** [comment]
And the accidental scrolls when scrolling with trackpad, are probably due to increase sensitivity within the app, I confirm that using sorayomi on the browser doesn't have the sensitivity issues.
