### ISSUE TITLE
[Feature Request] Option to change zoom key

### ISSUE THREAD

**Issue by Grimstonsd** [Suwayomi/Tachidesk-Sorayomi#138]
**Is your feature request related to a problem? Please describe.**
The default zoom key is to scroll up which is inconvenient when I just want to go back a little and it ends up zooming

**Describe the solution you'd like**
have the option to change the zoom key

**Describe alternatives you've considered**
another alternative would be the option to disable the zoom

**Comment by DattatreyaReddy** [comment]
Will consider this for next update

**Comment by Kickunio** [comment]
Is the 0.4.6 version connected with this feature request? Because the scroll up still zooms in the picture and doesn't scroll up the manga that's being read.

**Comment by DattatreyaReddy** [comment]
Nope, we still have to work on how to change the zoom key of mouse

**Comment by Kickunio** [comment]
Maybe the simpler option is to add ctrl + scroll up/down as a zoom option
