### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Eye0fSauron** [Suwayomi/Tachidesk-Sorayomi#145]
OS: Windows 7 
The app crashes on startup
tachidesk-sorayomi-0.4.6-windows-x64.msi
Error 0xc00007b

tachidesk-sorayomi-0.4.6-windows-x64.zip
api-ms-win-core-winrt-string-l1-1-0.dll is missing

Reinstalling Visual C++ did not lead to success

**Comment by DattatreyaReddy** [comment]
Sorry, @Eye0fSauron I couldn't replicate your problem when using Sorayomi on windows.

It may be a problem from your side. as I'm not specialized in windows Apps I may not be able to assist you.
