### ISSUE TITLE
Reverse proxy no longer works

### ISSUE THREAD

**Issue by geist325** [Suwayomi/Tachidesk-Sorayomi#175]
**Describe the bug**
I have Tachidesk running on Ubuntu 22.04, with a reverse proxy set up, DNS, and this configuration works on browser. With the latest update to Sorayomi on mobile, reverse proxy address displays Check your internet connection. Find works, but lists the local IP address, which will not work when I am outside of local network. Reverse proxy works both inside and outside of local network on browser. 

**To Reproduce**
1. Go to 'more'
2. Click on 'server url'
3. Enter 'http://sub.reverseproxyaddress.org'
4. See an "Check your Internet Connection" 

**Expected behavior**
On previous version, all of my sources and titles were present. Now only works with local IP listed for server. 

**Screenshots**
![Screenshot_20230415_110844](https://user-images.githubusercontent.com/37257796/232233161-8da372f2-6b73-438e-b502-41bbef8f7fb1.png)
![Screenshot_20230415_110853](https://user-images.githubusercontent.com/37257796/232233171-bf2b57f0-9e9e-4ef1-8f83-97f46eb0fe47.png)
![Screenshot_20230415_110931](https://user-images.githubusercontent.com/37257796/232233178-1cb5cfa3-a62b-435e-bc7a-c1c9d1a4fb0f.png)
![Screenshot_20230415_110935](https://user-images.githubusercontent.com/37257796/232233183-7c568347-cb0f-4410-9700-b6213e5d014f.png)

## Device information (Server)
- Tachidesk version: 0.7.0 r1197
- Server Operating System: Ubuntu 22.04
- Server Desktop Environment: N/A
- Server JVM version: 11.0.18
## Device information (Client)
- Client version: 0.5.2
- Client Type: Android
- Client Operating System: 13
- Client Specifications: Samsung S22
- (If the Client type is web) Client Web Browser: N/A

**Comment by DattatreyaReddy** [comment]
Disable Port in Server settings

**Comment by DattatreyaReddy** [comment]
https://user-images.githubusercontent.com/58727124/232233609-2b03e01c-d668-4153-ade2-942913521bf0.mov

**Comment by geist325** [comment]
Oops! Didn't check that, I guess it was reset. Thank you for the sanity check!

**Comment by DattatreyaReddy** [comment]
Sorry for that!, I've updated the release note.

need the port to be a separate integer for searching for server in local network 🥲
