### ISSUE TITLE
Chapter refresh

### ISSUE THREAD

**Issue by KhaosMonkey** [Suwayomi/Tachidesk-Sorayomi#19]
I am think a major feature would be too be able to kick off a chapter refresh of on the server from the app on your phone.

**Comment by Robonau** [comment]
chapter refresh should be done when you load the manga page (the page with the chapters list)

**Comment by KhaosMonkey** [comment]
My thought would be to be able to kick off an entire library refresh.

**Comment by Robonau** [comment]
there is currently no way of doing that with a reasonable amount of requests to the serverr

**Comment by KhaosMonkey** [comment]
Does it have to call back to the server for every library item? 

So if there was a script on the server that you could call to have it run a library refresh that would be ideal? So you have one call instead of multiple?

**Comment by Robonau** [comment]
currently yes

1 call is better than however many manga you have in library yes

the ideal is have it automated (as an option) so the user doesn't have to ever hit a button

**Comment by KhaosMonkey** [comment]
So untill the library refresh is implemented in the server side you guys really can't implement it on the app side. Sounds good. I'll close this issue. Thank you for the reply.
