### ISSUE TITLE
[Feature Request] refresh/redownload button for reader

### ISSUE THREAD

**Issue by TheRealNE0** [Suwayomi/Tachidesk-Sorayomi#190]
so i was just trying sorayomi feels incredible but after some chapters i face this issue. kinda don't know what happened, cleared cache, changed pages hoping it would fix problem but no luck and yes before you ask i checked the source website there supposed to be a picture which didn't load for some reason.

![Screenshot 2023-05-20 144113](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/46984761/f2616301-ee6c-4507-8492-6f68c883f61c)

So i want to know is it possible to add some sort of refresh/redownload button for every chapter in case we have faulty behavior like this so we can refresh/refetch whole chapter images in reader ?

**Comment by DattatreyaReddy** [comment]
You can download the chapter

**Comment by DattatreyaReddy** [comment]
On Windows 10 you can go to Settings -> System -> Storage -> Temporary Files and click remove files once its loaded

*this could be a temp fix

**Comment by TheRealNE0** [comment]
@DattatreyaReddy  thanks for the response, tried to clearing cache in app didn't work, tried to delete .webp files in tachidesk folder located in appdata didn't work either but it looks like your right and the issue is from tachidesk-server itself.

**Comment by TheRealNE0** [comment]
@DattatreyaReddy  thanks for the response, tried to clearing cache in app didn't work, tried to delete .webp files in tachidesk folder located in appdata didn't work either but it looks like your right and the issue is from tachidesk-server itself.
