### ISSUE TITLE
[Feature Request] Allow landscape view after installing PWA on mobile

### ISSUE THREAD

**Issue by picklepopper1** [Suwayomi/Tachidesk-Sorayomi#195]
**Is your feature request related to a problem? Please describe.**
Yes, after replacing the original webUI and installing it as a PWA on android through chrome, the app does not allow you to read in the landscape position. It's locked to portrait and is not possible after installing the PWA

**Describe the solution you'd like**
After installing the PWA, allow the app to accommodate the landscape view when the phone is rotated on it's side.

**Describe alternatives you've considered**
I could try and use it without installing it, but I'm using it sideways to deal with visual impairments. When not installed, the web toolbar is always present and takes up valuable screen real estate.

**Comment by DattatreyaReddy** [comment]
You can try Android Application https://github.com/Suwayomi/Tachidesk-Sorayomi/releases/tag/0.5.6

**Comment by picklepopper1** [comment]
The android app doesn't have zoom either as far as I'm aware. It's odd that zoom works in browser until the PWA is installed. 

Also, I'm aware of the magnifier, but I typically will zoom in like 125% and scroll from panel to panel, so I'd have to hold the magnifier down for as long as a reading session would last.

**Comment by DattatreyaReddy** [comment]
Hi @picklepopper1, Added Pinch to Zoom for mobile with the above mentioned PR

Thank you for raising the PR
