### ISSUE TITLE
When reading an unfinished chapter, all previous chapters are reset to unread and the last page read is displayed

### ISSUE THREAD

**Issue by eventhorizonsky** [Suwayomi/Tachidesk-Sorayomi#196]
**Describe the bug**
When reading an unfinished chapter, all previous chapters are reset to unread and the last page read is displayed

**To Reproduce**
1. Open a comic with an unread chapter
2. Quit after reading an unread chapter for a while
3. See an error

**Screenshots**
![20230528211854](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/60322987/239c1809-1d02-49ec-a09a-bbe91c704d45)

## Device information (Server)
- Tachidesk version: (v0.7.0)
- Server Operating System: (win10)
- Server Desktop Environment: N/A 
- Server JVM version: bundled with win32 or (Example: Java 8 Update 281 or OpenJDK 8u281)
## Device information (Client)
- Client version: (v0.5.6)
- Client Type: (Web, Android, Linux, Windows.)
- Client Operating System: (win10,Android)

**Comment by DattatreyaReddy** [comment]
Found the issue thank you for reporting
