### ISSUE TITLE
[Bug] "ok" button is missing in the popup to filter extensions

### ISSUE THREAD

**Issue by RaphaelHacques** [Suwayomi/Tachidesk-Sorayomi#199]
Small description for small issue 😄

Describe the bug
(Tested on ios/uwp) The "ok" button is missing from the popup to filter extensions based on language.

To Reproduce
Sources -> Languages button ...

**Comment by DattatreyaReddy** [comment]
there is no `ok` button 
- you toggle it to apply directly
- (If it is a check box then it can have ok button but if it is toggle there is no need)

**Comment by DattatreyaReddy** [comment]
Ill Update the `cancel` text to `Close`.
