### ISSUE TITLE
I have a big issue 

### ISSUE THREAD

**Issue by Chahinphone** [Suwayomi/Tachidesk-Sorayomi#208]
Hi guys 
I have an issue with application he tell me
 check your internet connection sorayomi and i have internet 
And i wana know what is the server
![Screenshot_2023-07-24-22-20-37-907_com suwayomi tachidesk_sorayomi](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/140453919/c9d6db3d-45d6-4323-8bdb-6abaf081c7ae)

Thank you

**Comment by Chahinphone** [comment]
Please can u answer 😭

**Comment by DattatreyaReddy** [comment]
- You need to run [Tachidesk Server](https://github.com/Suwayomi/Tachidesk-Server/releases/tag/v0.7.0) in your PC.
- If you already running it then your mobile app need to be in the same network of your PC
- If it is in same network then click Find button in above picture to find your server address 
this will fix your issue

**Comment by Chahinphone** [comment]
Thank you but I don't have pc 
Please fux it to work without pc 
And i wish you the best 🙏

**Comment by DattatreyaReddy** [comment]
Then Use Tachiyomi. (Tachidesk is for PC)

**Comment by Chahinphone** [comment]
That's great thank you very much 😊
