### ISSUE TITLE
I can't install extensions on my macos, botho on tachidesk and sorayomi

### ISSUE THREAD

**Issue by SageFaruqV** [Suwayomi/Tachidesk-Sorayomi#214]
**Describe the bug**
I'm unable to install any extension at all on my macos for sorayomi

**To Reproduce**
1. Go to extensions 
2. Click install on any extension at all
4. See an error
![Screenshot 2023-08-04 at 19 40 22](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/136016032/79155e3c-9440-41b5-aeab-232913349c5a)

**Expected behavior**
It either says internet connection unavailable or it shows a sort of error with a code

## Device information (Server)
- Tachidesk version: (Example: v0.2.3-r255-win32)
- Server Operating System: (Example: Ubuntu 20.04)
- Server Desktop Environment: N/A or (Example: Gnome 40)
- Server JVM version: bundled with win32 or (Example: Java 8 Update 281 or OpenJDK 8u281)
## Device information (Client)
- Client version: (Example: 0.1.1)
- Client Type: (Example: Web, Android, Linux, Windows.)
- Client Operating System: (Example: Ubuntu 20.04)
- Client Specifications: (Example: Pixel 4a)
- (If the Client type is web) Client Web Browser: (Example: Google Chrome 89.0.4389.82)

<img width="1680" alt="Screenshot 2023-08-04 at 19 40 22 (2)" src="https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/136016032/cbd5ba9a-b265-4923-ac27-949475e9f337">
![Screenshot 2023-08-04 at 19 40 40](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/136016032/0252cbe2-9f74-440d-903d-17291dc5a423)

**Comment by DattatreyaReddy** [comment]
You need to ask that in Tachidesk server repo
