### ISSUE TITLE
Cannot find any chapters on Sorayomi 

### ISSUE THREAD

**Issue by Cluster321** [Suwayomi/Tachidesk-Sorayomi#215]
**Describe the bug**
Hello. I cannot find chapters on the latest Sorayomi version. They only appear in the older version. 

**To Reproduce**
1. Go to 'Library'
2. Click on a random manga
4. See no chapters to the right.

**Expected behavior**
I expect the chapters to show up exactly like they do on the older version.

**Screenshots**
<img width="843" alt="42142" src="https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/109810756/b761f009-fe16-4435-b460-384f3271ae88">

## Device information (Server)
- Tachidesk version: v0.7.0-r1197-winx64
- Server Operating System: (Example: Windows 10)
- Server JVM version: Java 8 Update 381 
## Device information (Client)
- Client version: (Example: 0.5.9)

**Comment by DattatreyaReddy** [comment]
You need to check your filters

[ --- ] - Filter not applied 
[     ] - Filter Disabled
[ ✓ ] - Filter enabled

**Comment by Cluster321** [comment]
> 

Awesome. That did it. Thank you!
