### ISSUE TITLE
Safari will keep alerting basic auth challenge

### ISSUE THREAD

**Issue by KiriKira** [Suwayomi/Tachidesk-Sorayomi#225]
Describe the bug
Safari will keep alerting basic auth challenge if the backend library enabled basic auth

To Reproduce

1. run tachidesk-server via docker with latest image
2. enable basic auth of the library
3. put sorayomi web 0.5.10 in webUI directory
4. use Safari on ios (ipad/iphone) to access the web and set server credential correctly
5. login alert of basic auth will keep appearing when access library every time. Even if access can be continued by simply clicking on the cancel

Expected behavior
should be working like on other browser/platform, just login once. don't know if it is a bug or just Safari's bad

Device information (Server)
Tachidesk version: ghcr.io/suwayomi/tachidesk:v0.7.0-ubuntu
Server Operating System: docker
Server Desktop Environment: N/A
Server JVM version: N/A
Device information (Client): ipad/iphone
Client version: 0.5.10
Client Type:Web
Client Web Browser: Safari 16.6

**Comment by DattatreyaReddy** [comment]
Hi @KiriKira,
Thank you for raising this bug. This needs to be fixed from both the Server and Sorayomi, so it may take time to implement.
