### ISSUE TITLE
Split wide images

### ISSUE THREAD

**Issue by KiriKira** [Suwayomi/Tachidesk-Sorayomi#226]
**Is your feature request related to a problem? Please describe.**
Wider images, usually from scanned comic books, are not suitable for viewing directly on mobile devices, especially small screens

**Describe the solution you'd like**
offer a switch for splitting wide images into two images like tachiyomi do

**Describe alternatives you've considered**
I understand that this functionality may require tachidesk-server to be implemented in conjunction with it, if it's difficult or not in the plans I'll cut the source file myself using scripts

**Additional context**
Many thanks for your extraordinary work!

**Comment by DattatreyaReddy** [comment]
> **Describe alternatives you've considered** I understand that this functionality may require Tachidesk-server to be implemented in conjunction with it, if it's difficult or not in the plans I'll cut the source file myself using scripts

As you've mentioned it needs to be implemented on the Server side. so please raise the issue in Tachidesk-server.

(If it is not in the plans of the Server then we may look into it)

**Comment by KiriKira** [comment]
Hi @DattatreyaReddy , you are right, I have create a issue https://github.com/Suwayomi/Tachidesk-Server/issues/678 . Hopefully this useful application will be implemented!Hopefully this useful feature will be implemented!
