### ISSUE TITLE
[Feature Request] Option to move between chapters while reading.

### ISSUE THREAD

**Issue by NiamhFerns** [Suwayomi/Tachidesk-Sorayomi#228]
**Is your feature request related to a problem? Please describe.**
Currently reading manga with especially (1-10 pages) shorter chapters is rather annoying. You need to open read then go back and reopen the next one. 

**Describe the solution you'd like**
It would be nice if there was an option to enable moving between chapters. This way if you reach the end of a chapter, hitting the movement button will automatically move you to the next chapter. Same if you're at the beginning of a chapter and you move back a page.

**Describe alternatives you've considered**
There aren't really many better alternatives for this other than going into each chapter manually, reading, then going back out again. This, for me at least, just takes me out of the experience.

**Comment by DattatreyaReddy** [comment]
This feature is already there!
<img width="868" alt="Screenshot 2023-09-26 at 2 05 51 PM" src="https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/58727124/37b617f9-81df-491f-a480-11bd4a21d7cc">
On Desktop:
- you can use `arrow keys` or `WASD` keys to change chapter
On Mobile:
- You can use swipe gestures to change

**Comment by BeanBorrido** [comment]
Doesn't work for me with arrow keys or WASD. Allows me to move between pages with arrow keys but not chapters. Running Version 5.10.0 on EndeavourOS, Linux, installed through AUR. Works fine when clicking the UI. 

Reading mode: Single Horizontal (RTL).

**Comment by DattatreyaReddy** [comment]
Top and bottom arrows should work though.
W and S too

**Comment by BeanBorrido** [comment]
Ah, got it. Sorry that's completely my bad.
