### ISSUE TITLE
[Feature Request] <issue templates>

### ISSUE THREAD

**Issue by Robonau** [Suwayomi/Tachidesk-Sorayomi#23]
## What feature should be added to Tachidesk?
issue templates, should probably copy from the rest of Tachidesk

##  Why/Project's Benefit/Existing Problem
without issue templates you aren't gonna get as useful information from users

**Comment by DattatreyaReddy** [comment]
Created Issue templates for Bug reports and Feature requests.
Default Github temples with few changes from Tachidesk
