### ISSUE TITLE
Reader stucks on grey logo screen after 0.5.12/0.5.14

### ISSUE THREAD

**Issue by VEWION** [Suwayomi/Tachidesk-Sorayomi#234]
**Describe the bug**
After upgrading to 0.5.12/0.5.14, manga won't be displayed and stuck on a grey logo screen. Downgrading to 0.5.11 can be resolved. Developer Tools Console is saying "Unsupported operation: Platform._operatingSystem". Status inside Network are all 200 with no error.

**To Reproduce**
1. Click on any manga no matter it is Downloaded or not.

**Expected behavior**
Displaying manga.

**Screenshots**
![螢幕擷取畫面 2023-10-15 140923](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/56110451/d0626087-f911-4622-ae84-c7c6ef87c17c)
![螢幕擷取畫面 2023-10-15 143528](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/56110451/45b6e312-a171-466d-950d-43d943282e3c)

## Device information (Server)
- Tachidesk version: ghcr.io/suwayomi/tachidesk:preview Tachidesk-Server Preview v0.7.0-r1384
- Server Operating System: Synology DSM 7.2 Docker
- Server Desktop Environment: N/A
- Server JVM version: N/A
## Device information (Client)
- Client version: 0.5.12/0.5.14
- Client Type: Web/iOS PWA
- Client Operating System: Windows 11/iOS 17.0.3
- Client Specifications: PC/iPhone
- Client Web Browser: Microsoft Edge 118.0.2088.46/iOS 17.0.3 Safari

**Comment by DattatreyaReddy** [comment]
found the issue thank you for reporting
