### ISSUE TITLE
Reader initial overlay toggle not working and can't be translated

### ISSUE THREAD

**Issue by VEWION** [Suwayomi/Tachidesk-Sorayomi#238]
**Describe the bug**
Firstly I don't know if the toggle "Added Disable Reader Layout Overlay Animation toggle" in the release notes means the toggle "Reader initial overlay" inside Settings->Reader? After turning it off it just keeps the setting before opening a manga. If I open any manga the Reader initial overlay will turn on automatically. I also can't find the string in Weblate so it can't be translated.

**To Reproduce**
1. Go to 'Settings->Reader'
2. Click on 'Reader initial overlay' and toggle off, it stays off no matter switching any other pages
3. Click on any episode, the Reader Navigation layout shows up
4. Go back to 'Settings->Reader' and the toggle is back on automatically

**Expected behavior**
Toggle it off and not showing layout overlay anymore

## Device information (Server)
- Tachidesk version: ghcr.io/suwayomi/tachidesk:preview Tachidesk-Server Preview v0.7.0-r1384
- Server Operating System: Synology DSM 7.2 Docker
- Server Desktop Environment: N/A
- Server JVM version: N/A
## Device information (Client)
- Client version: 0.5.15
- Client Type: Web/iOS PWA
- Client Operating System: Windows 11/iOS 17.0.3
- Client Specifications: PC/iPhone
- Client Web Browser: Microsoft Edge 118.0.2088.46/iOS 17.0.3 Safari

**Comment by DattatreyaReddy** [comment]
Sorry that's my fault (can't find the right word made it too complicated and ambiguous)
`Reader initial Overlay` is the top chapter name and bottom quick settings.
Also, there seems to be a bug, which automatically turns on the toggle. Ill fix it

**Comment by VEWION** [comment]
It’s ok:)
I am sorry does it means the "Disable Reader Layout Overlay Animation toggle" is not the same as "Reader initial overlay toggle"? I can’t find the former in web settings.
Would it be better if the "Reader initial overlay" changes to something like "Show UI on start" or add it as description just like the "Swipe toggle"?
String for the translation will be also added in Weblate too?
Also I found new version doesn’t saving reading record anymore. Don’t know if this is related to recent changes. I am going to try revert to older version and see later this day.

**Comment by DattatreyaReddy** [comment]
Well, now I see it release notes are wrong 😑 . I've added `Reader initial overlay toggle` and the reader layout animation will be disabled when changing the chapter.
