### ISSUE TITLE
Self-Hosting Tachidesk-Server

### ISSUE THREAD

**Issue by brukberhane** [Suwayomi/Tachidesk-Sorayomi#24]
**Is your feature request related to a problem? Please describe.**
It would be nice if Sorayomi was able to self-host Tachidesk-Server on the desktop platforms.

**Describe the solution you'd like**
A possible solution to accomplish this could be to bundle Tachidesk-Server with the applications and configure/run it with the help of the [process_run](https://github.com/tekartik/process_run.dart) dart package

**Describe alternatives you've considered**
Another possible solution could be giving the ability to the client to run independently of the server and be able to cache downloads locally

**Comment by DattatreyaReddy** [comment]
For now, we don't have plans to ship Tachidesk-server with Tachidesk-Sorayomi as we are concentrating on making the app as small as possible.

But I really like the [process_run](https://pub.dev/packages/process_run) package and I also found that it had Linux `which` function to find executables. So, maybe we could implement it to run the Server on startup or something like that.

**Comment by brukberhane** [comment]
I think that's great! Should work just as well
