### ISSUE TITLE
Terrible performance with displaying large download queue

### ISSUE THREAD

**Issue by qu1ck** [Suwayomi/Tachidesk-Sorayomi#247]
**Describe the bug**
For a large download queue (>1000 items) performance drops to the point of app freezing for multiple seconds on scroll or any update. Happens both on pc and android versions.

**To Reproduce**
Add a bunch of manga with many chapters to download queue at once. Navigate to downloads tab, try to scroll.
**Expected behavior**
Scrolling is responsive and app does not freeze.

## Device information (Server)
- Tachidesk version: v0.7.0-r1393
- Server Operating System: official docker image
- Server Desktop Environment: N/A
- Server JVM version: whatever comes in the docker image
## Device information (Client)
- Client version: v0.5.17
- Client Type: Android, Windows
- Client Operating System: Android, Windows
- Client Specifications: Ryzen 3900x PC, midrange android 13 phone

**Additional context**
I am not familiar with flutter but if it's anything like react then this list should be virtualized and items outside of the view should not be rendered.

**Comment by DattatreyaReddy** [comment]
Download List is rendered based on visibility.
IDK why it is getting frozen. 
ill check it thank you for reporting
