### ISSUE TITLE
unable to specify https certificates

### ISSUE THREAD

**Issue by Razmo99** [Suwayomi/Tachidesk-Sorayomi#255]
G'day Love the app,

Decided to enable Https on Nginx which I am running the Tachidesk server through. Was able to get the desktop version (windows )on Sorayomi working by installing the public crt in the certificate store no problem. 

The android app doesn't appear to have any way to get it to trust a self signed certificate :( 
I've installed my certificate within the CA Authority store on my Android. Chrome works for Tachideks webUI without a certificate error, Sorayomi atm  just says check your internet connection , I'm confident this is a Cert trust issue

Are we able to allow the app to trust user certificates or add an option to specify a certificate for the https connection within the app

Cheers

---

**Describe the bug**
Unable to connect to a Tachidesk server that is using Https with Sorayomi

**To Reproduce**
1. Connect to a https enabled Tachidesk server with a self signed certificate from an android device
2. it will fail to connect

**Expected behavior**
Should be able to connect to a Tachidesk server using https

## Device information (Server)
- Tachidesk version: preview 0.70 r1424
- Server Operating System: Ubuntu 20.04
- Using Docker Compose
## Device information (Client)
- Client version: 12
- Client Type: Mobile
- Client Operating System: Android
- Client Specifications: Samsung S10

**Comment by DattatreyaReddy** [comment]
Ill try to fix this issue in next release.
Sorry for the late replay.
