### ISSUE TITLE
Edit category menu does not need a menu

### ISSUE THREAD

**Issue by qu1ck** [Suwayomi/Tachidesk-Sorayomi#258]
**Is your feature request related to a problem? Please describe.**
There is no point to have a menu with single item, it can be just a button. Same as labels button in tachidesk web ui

![image](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/3622532/8a2945b7-38bc-4cba-97ef-4ecf9b80835e)

Why have 2 clicks when 1 click can suffice.

**Describe the solution you'd like**
Replace it with a button.

**Describe alternatives you've considered**
I suppose it can be a dropdown with checkboxes of categories. That will save another unnecessary click on Close button.

**Comment by DattatreyaReddy** [comment]
Hi @qu1ck,
In mobile (Small Screens, you can resize the screen) the refresh button goes into the menu, and it will have 2 buttons.
we could do as you suggested (ill try to do that in by next release)
