### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by ishanvaghani** [Suwayomi/Tachidesk-Sorayomi#259]
Recently, I started making open-source contributions. This project looks really interesting to me. Let me know how I can contribute to this project (with any bug fixes, features, or improvements)

**Comment by DattatreyaReddy** [comment]
Hi @ishanvaghani, 
You can pick the issues from the Issues section or you can start using the app and try to implement the features that you think are needed.
Raise a PR for the said feature ill try to merge it ASAP
