### ISSUE TITLE
True Black Background

### ISSUE THREAD

**Issue by chrigi** [Suwayomi/Tachidesk-Sorayomi#263]
**Is your feature request related to a problem? Please describe.**
In the reader view the pages sit on a grey-ish background instead of true black. On OLED phones it would be preferrable to have the option to set this to black in the reader mode at least and on iPhones with a notch/island this leads to a display inconsistency as the statusbar will be completely black around the notch/island and the page then sits on the grey-ish background.

**Describe the solution you'd like**
An option to set the background to true black in the reader view.

**Describe alternatives you've considered**
None

**Additional context**
![IMG_2734](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/40846/83585409-0141-40c6-a29e-16d280569f98)

**Comment by chrigi** [comment]
@DattatreyaReddy Thanks for the incredibly fast release of this 😄 One more thing though:
True dark fixes the issue of the reader background not going into the statusbar & navigation bar simply because you can't see it anymore but I still think the reader background should cover the whole screen if active and not just the safe area.

**Comment by DattatreyaReddy** [comment]
Raise another feature request for this (then again reader will go under noch which is not exactly a desirable thing)
