### ISSUE TITLE
Tachidesk showing this error "Library Could not load categories Request failed with status code 500"

### ISSUE THREAD

**Issue by Divyam-Naudiyal** [Suwayomi/Tachidesk-Sorayomi#289]
![Screenshot 2024-02-05 205346](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/118731194/c79efcc7-983c-4b84-b3b8-e8e38acd0205)

**Comment by DattatreyaReddy** [comment]
Sorry, but your UI is Tachiyomi WebUi and this is Sorayomi UI please open the issue at https://github.com/Suwayomi/Suwayomi-WebUI or
https://github.com/Suwayomi/Suwayomi-Server

**Comment by bosskham** [comment]
> Sorry, but your UI is Tachiyomi WebUi and this is Sorayomi UI please open the issue at https://github.com/Suwayomi/Suwayomi-WebUI or https://github.com/Suwayomi/Suwayomi-Server

Dude it's bug don't you list to @Divyam-Naudiyal at all? It's bug that he's try to find the solution it the latest suwayomi server + webui, you are totally idiot @DattatreyaReddy
