### ISSUE TITLE
[Feature-Request] Filter by scanlater group for sources with multiple.

### ISSUE THREAD

**Issue by demon2749** [Suwayomi/Tachidesk-Sorayomi#309]
**Is your feature request related to a problem? Please describe.**
Some of the most functional extensions aggregate from multiple sources. Take Comick for example. When you have multiple scanlator groups uploading the same chapter, you often end up with multiple entries in the app.

**Describe the solution you'd like**
An elegant solution used in Jays2Kings/tachiyomiJ2K is to filter these by the scanlator string. This can clear up most/all of the duplicate chapters as you read.

**Describe alternatives you've considered**
An alternative would be to look for a followup chapter by the same scanlator while you read, enabling a clean transition to the next chapter. This doesn't seem to happen as-is.

**Additional context**
Screenshots from Jays2Kings/tachiyomiJ2K
![Screenshot_20240904-153025_TachiyomiJ2K](https://github.com/user-attachments/assets/2f9fd6d3-9c09-465f-9027-f9f4357d9bfb)
![Screenshot_20240904-152812_TachiyomiJ2K](https://github.com/user-attachments/assets/5dfab2be-a38d-4797-8c98-409d496f3424)
![Screenshot_20240904-152822_TachiyomiJ2K](https://github.com/user-attachments/assets/1687a8a1-be78-462e-9ac7-da63aa782b19)
![Screenshot_20240904-152832_TachiyomiJ2K](https://github.com/user-attachments/assets/e4a4d836-2e0c-4d7a-8fe6-a60c20e551f4)

**Comment by DattatreyaReddy** [comment]
Already exists
