### ISSUE TITLE
Save current page as image

### ISSUE THREAD

**Issue by matthewdias** [Suwayomi/Tachidesk-Sorayomi#36]
**Is your feature request related to a problem? Please describe.**
I don't have a good way to quickly save pages for sharing

**Describe the solution you'd like**
Add a long press action or top toolbar button to download/save a chapter as image to device filesystem

**Describe alternatives you've considered**
Maybe a share button instead of download

**Comment by DattatreyaReddy** [comment]
Implemented this feature. check #41.
For android, App will open the image on the web for now.
Thankyou for your feature request.
