### ISSUE TITLE
Tap page to bring up controls

### ISSUE THREAD

**Issue by matthewdias** [Suwayomi/Tachidesk-Sorayomi#37]
**Is your feature request related to a problem? Please describe.**
The small eye icon is hard to reach especially on tablets and makes accessing controls cumbersome. The eye icon always visible is also annoying.

**Describe the solution you'd like**
If you tap anywhere on the page (except sides when tapping sides to switch pages is enabled) the controls should show up.

**Additional context**
It would be nice to have the previous/next chapter buttons shown when tapping too, so you dont have to do two taps to see those, but maybe that can be a separate issue after this one.

**Comment by DattatreyaReddy** [comment]
Implemented Tap to toggle controls. check #42
Thank you for opening this Feature request.
