### ISSUE TITLE
Action on multiple chapters at once

### ISSUE THREAD

**Issue by matthewdias** [Suwayomi/Tachidesk-Sorayomi#39]
**Is your feature request related to a problem? Please describe.**
It's very slow to action on many chapters at one time

**Describe the solution you'd like**
allow selecting multiple chapters so that you can perform actions on them all at once:
- mark read/unread
- download or remove download
- bookmark

**Additional Context**
Apparently this needs a server endpoint for batch operations before it can be implemented

**Comment by DattatreyaReddy** [comment]
This is a feature that needs to be implemented on the server-side.

**Comment by Robonau** [comment]
> Can this not be achieved by sending multiple requests to the server? There should be a delay of about 1 - 5 seconds to avoid spamming the server and making it crash but it does seem doable client side albeit a bit tedious

whilst this is doable it is not ideal
as such UI devs are willing to wait for the server devs to add the feature

**Comment by DattatreyaReddy** [comment]
Releases in V0.3.0
