### ISSUE TITLE
Make the difference between read and unread chapters more obvious

### ISSUE THREAD

**Issue by matthewdias** [Suwayomi/Tachidesk-Sorayomi#40]
**Is your feature request related to a problem? Please describe.**
It is hard to distinguish between read and unread chapters in the chapter list, especially on Windows

**Describe the solution you'd like**
Maybe make the source and date text bold, as well. (the chapter title already is)

**Describe alternatives you've considered**
Could also use a heavier font weight for unread

**Additional context**
![image](https://user-images.githubusercontent.com/3302524/162596073-e943a58c-9471-4e5b-a526-4dc2bf441fb0.png)

**Comment by DattatreyaReddy** [comment]
Implemented this feature. check #41.
Made Unread Chapters Bold.
Thank you for your feature request.
