### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by matthewdias** [Suwayomi/Tachidesk-Sorayomi#57]
**Is your feature request related to a problem? Please describe.**
I want to look at pages closer

**Describe the solution you'd like**
Let me pinch to zoom

**Describe alternatives you've considered**
Double tap for some reasonable default zoom level

**Additional context**
On desktop this steals priority over mouse wheel scrolling so a workaround is needed until that is changed on Flutters end

**Comment by DattatreyaReddy** [comment]
https://github.com/flutter/flutter/issues/64210

**Comment by ShaolinSnake96** [comment]
No one ever took that essensial request, worse team ever
