### ISSUE TITLE
Client-side downloads

### ISSUE THREAD

**Issue by matthewdias** [Suwayomi/Tachidesk-Sorayomi#58]
**Is your feature request related to a problem? Please describe.**
I can't read while offline and page loading can be slow

**Describe the solution you'd like**
Let me save chapters for offline reading in the app

- maybe also include a badge number for client downloads vs server downloads

**Comment by DattatreyaReddy** [comment]
This is not possible as it requires a fundamental change in the architecture of Sorayomi.
