### ISSUE TITLE
Web config file

### ISSUE THREAD

**Issue by binyaminyblatt** [Suwayomi/Tachidesk-Sorayomi#60]
I was wondering if there's some way to include a config file for the web version of the app to point it at my personal server instead of having to manually configure it every time I open it on a new device

**Comment by DattatreyaReddy** [comment]
I will try to implement it in next release.

**Comment by binyaminyblatt** [comment]
Thanks

**Comment by DattatreyaReddy** [comment]
Does having the Sorrayomi web take the base URL as server address sufficient (Same as WebUI)?
for example: 
```
base URL = http://suwayomi.com/library
then app will take http://suwayomi.com/ as server address (same as WebUi)
```

**Comment by binyaminyblatt** [comment]
how do i set it up do i put a json file next to the index file??

**Comment by DattatreyaReddy** [comment]
> how do i set it up do i put a json file next to the index file??
Haven't implemented This feature as requested.
Instead, In web sorayomi will take the base url as server url in default settings.

Reason: Tachidesk-server has added a new feature to change the default webUI to Sorayomi. So, Having sorayomi to use base url would be an ideal feature ( webUI  also works the same)

You can find `changing webUI` feature in `Tachidesk-server-preview` for now.
