### ISSUE TITLE
Choose the level of zoom on the Reader

### ISSUE THREAD

**Issue by Omar7340** [Suwayomi/Tachidesk-Sorayomi#83]
When you are reading webtoons, the image take all the place on the screen and makes the page a bit blurry so maybe let the user choose the level of zoom will be a better experience.

(On desktop windows version)

exemple : 
![image](https://user-images.githubusercontent.com/38433787/201783083-d96f3fae-32b5-454f-b137-16446c568d30.png)

**Comment by DattatreyaReddy** [comment]
> When you are reading webtoons, the image take all the place on the screen and makes the page a bit blurry so maybe let the user choose the level of zoom will be a better experience.
> 
> (On desktop windows version)
> 
> exemple : ![image](https://user-images.githubusercontent.com/38433787/201783083-d96f3fae-32b5-454f-b137-16446c568d30.png)

Will try to implement it in the newer versy

**Comment by DattatreyaReddy** [comment]
So, @OOmar-pro the thing is that Flutter Widget which manages the Zoom action will only support having zoom from all sides.
means, when you zoom out it will zoom out the pictures equally. ( Same margin from all sides ).

So, we can't implement it for now

**Comment by DattatreyaReddy** [comment]
Added in release v0.4.2
